apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vets-api
  annotations:
    github.com/project-slug: department-of-veterans-affairs/vets-api
spec:
  type: public
  lifecycle: beta
  owner: 'test@adhocteam.us'
