version: '3.4'
services:
  postgres:
    extends:
      file: docker-compose.test.yml
      service: postgres
  vets-api:
    extends:
      file: docker-compose.test.yml
      service: vets-api
    tmpfs:
      - /tmp
volumes:
  test_bundle:
    external: true
