---
  :method: :get
  :body:
    error_occurred: false
    error_message: null
    status: null
    debug_info: null
    data:
      result:
        partial: false
        sources:
        - VVS
        - '983'
        - '984'
        pageCount: 1
        currentPage: 1
      appointmentList:
      - id: '202101281500983000089800000000000000'
        startDate: '2021-01-28T15:00:00Z'
        clinicId: '898'
        facilityId: '983'
        sta6aid: 983GD
        stationName: CHYSHR-Loveland VA Clinic
        locationName: LVLND  SOCIAL WORK
        patientIcn: 1012845331V153043
        communityCare: false
        vdsAppointments:
        - id: 898;20210128.080000
          appointmentTime: '2021-01-28T15:00:00Z'
          clinic:
            name: LVLND  SOCIAL WORK
            askForCheckIn: false
            facilityCode: '983'
          patientId: '7216691'
          type: SERVICE CONNECTED
          currentStatus: CANCELLED BY PATIENT
      - id: '202101281600983000113500000000000000'
        startDate: '2021-01-28T16:00:00Z'
        clinicId: '1135'
        facilityId: '983'
        sta6aid: '983'
        stationName: CHYSHR-Cheyenne VA Medical Center
        locationName: CHY PHARMACY
        patientIcn: 1012845331V153043
        communityCare: false
        vdsAppointments:
        - id: 1135;20210128.090000
          appointmentTime: '2021-01-28T16:00:00Z'
          clinic:
            name: CHY PHARMACY
            askForCheckIn: false
            facilityCode: '983'
          patientId: '7216691'
          type: SERVICE CONNECTED
          currentStatus: CANCELLED BY PATIENT
      - id: '202109171910983000084800000000000000'
        startDate: '2021-09-17T19:10:00Z'
        clinicId: '848'
        clinicFriendlyName: CHY PC VAR2
        facilityId: '983'
        sta6aid: '983'
        stationName: CHYSHR-Cheyenne VA Medical Center
        locationName: CHY PC VAR2
        patientIcn: 1012845331V153043
        communityCare: false
        vdsAppointments:
        - id: 848;20210917.131000
          appointmentLength: '20'
          appointmentTime: '2021-09-17T19:10:00Z'
          clinic:
            name: CHY PC VAR2
            askForCheckIn: false
            facilityCode: '983'
          patientId: '7216691'
          type: REGULAR
          currentStatus: FUTURE
          bookingNote: 'New issue: new medical issue.  new medical issue.  new medical
            issue.  new medical issue.  new medical issue.  new medical issue.  new medical
            issue.'
      - id: '202111051930983000084800000000000000'
        startDate: '2021-11-05T19:30:00Z'
        clinicId: '848'
        clinicFriendlyName: CHY PC VAR2
        facilityId: '983'
        sta6aid: '983'
        stationName: CHYSHR-Cheyenne VA Medical Center
        locationName: CHY PC VAR2
        patientIcn: 1012845331V153043
        communityCare: false
        vdsAppointments:
        - id: 848;20211105.133000
          appointmentTime: '2021-11-05T19:30:00Z'
          clinic:
            name: CHY PC VAR2
            askForCheckIn: false
            facilityCode: '983'
          patientId: '7216691'
          type: REGULAR
          currentStatus: CANCELLED BY PATIENT
      numAppointments: 20
  :headers:
    Cache-Control: no-cache
    Pragma: no-cache
    Content-Length: '77249'
    Content-Type: application/json; charset=utf-8
    Expires: "-1"
    Server: Microsoft-IIS/7.5
    X-Aspnet-Version: 4.0.30319
    X-Powered-By: ASP.NET
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: GET, PUT, POST, DELETE, HEAD
    Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
    Date: Fri, 20 Jul 2018 15:38:45 GMT
  :status: 200
