veteranInformation:
    fullName: [identity_information, full_name]
    ssn: [identity_information, ssn]
    dob: [identity_information, date_of_birth]
cellPhone: [contact_information, us_phone]
emailAddress: [contact_information, email]
isLoggedIn: [is_logged_in]