name: test_and_build
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 2
      BUNDLE_RETRY: 3
      LANG: en_US.UTF-8
      PGHOST: postgres
      PGUSER: vets-api
      RAILS_ENV: test
      "Settings.test_database_url": "postgis://vets-api:postgres@127.0.0.1:5432/vets_api_test?pool=4"     
      "Settings.saml.cert_path": "spec/support/certificates/ruby-saml.crt"
      "Settings.saml.key_path": "spec/support/certificates/ruby-saml.key"
      "Settings.binaries.clamdscan": "clamscan"

    services:
      postgres:
        image: postgis/postgis:11-2.5
        env:
          POSTGRES_USER: vets-api
          POSTGRES_DB: vets-api_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

      redis:
        image: circleci/redis:3.2-alpine


    steps:
      - uses: actions/checkout@v2 #checkout step
      - uses: ruby/setup-ruby@v1
      - name: Install dependencies (pdftk, poppler, imagemagick)
        run: sudo apt install imagemagick pdftk poppler-utils

      - name: Gem Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gem-cache-${{ matrix.image }}-${{ hashFiles('Gemfile.lock') }}

      - name: Install Dependencies
        run: bundle install --path vendor/bundle
  
      - name: Audit bundled gems for CVE issues
        run:  bundle exec bundle-audit check --update
        
      - name: Static security analysis using Brakeman
        run:  bundle exec brakeman --exit-on-warn --run-all-checks --confidence-level=2
 
      - name: Lint code with Rubocop
        run: bundle exec rubocop -r rubocop-thread_safety --parallel --format progress
#         env:
#           RAILS_ENV: test
#           POSTGRES_USER: postgres
#           POSTGRES_DB: vets-api_test          
#           POSTGRES_PASSWORD: ""
#           POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
#         run: bundle exec rake db:create db:schema:load
#       - name: Run Specs
#         run: bundle exec rspec --pattern spec/**/*_spec.rb --pattern modules/*/spec/**/*_spec.rb --format progress --format RspecJunitFormatter -o ./rspec/rspec.xml --format html --out ./ci/rspec.html


  tests:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 2
      BUNDLE_RETRY: 3
      LANG: en_US.UTF-8
      PGHOST: postgres
      PGUSER: vets-api
      RAILS_ENV: test
      "Settings.test_database_url": "postgis://vets-api:postgres@127.0.0.1:5432/vets_api_test"   
      "Settings.saml.cert_path": "spec/support/certificates/ruby-saml.crt"
      "Settings.saml.key_path": "spec/support/certificates/ruby-saml.key"
      "Settings.binaries.clamdscan": "clamscan"

    services:
      postgres:
        image: circleci/postgres:11.5-postgis-ram # 11.5 engine on AWS RDS
        env:
          POSTGRES_USER: vets-api
          POSTGRES_DB: vets-api_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

      redis:
        image: circleci/redis:3.2-alpine


    steps:
      - uses: actions/checkout@v2 #checkout step
      - uses: ruby/setup-ruby@v1
      - name: Install dependencies (pdftk, poppler, imagemagick)
        run: sudo apt install imagemagick pdftk poppler-utils

      - name: Gem Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gem-cache-${{ matrix.image }}-${{ hashFiles('Gemfile.lock') }}

      - name: Install Dependencies
        run: bundle install --path vendor/bundle

      - name: Setup Database
        env:
          POSTGRES_USER: vets-api
          POSTGRES_DB: vets-api_test
          POSTGRES_PASSWORD: postgres
          RAILS_ENV: test
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          DATABASE_URL: "postgis://vets-api:postgres@127.0.0.1:5432/vets_api_test?pool=4"  
        run: bundle exec rake db:setup
