name: test_and_build
on: [push]
jobs:
  specs:

    strategy:
      matrix:
        ruby: [2.6.6]

    runs-on: ubuntu-latest
    container: circleci/ruby:2.6.6-stretch
    env:
      BUNDLE_JOBS: 2
      BUNDLE_RETRY: 3
      LANG: en_US.UTF-8
      PGHOST: localhost
      PGUSER: vets-api
      RAILS_ENV: test
      "Settings.saml.cert_path": "spec/support/certificates/ruby-saml.crt"
      "Settings.saml.key_path": "spec/support/certificates/ruby-saml.key"
      "Settings.binaries.clamdscan": "clamscan"

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: vets-api
          POSTGRES_DB: vets-api_test
          POSTGRES_PASSWORD: ""
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: circleci/redis:3.2-alpine


    steps:
      # This Docker file changes sets USER to circleci instead of using the default user, so we need to update file permissions for this image to work on GH Actions.
      # See https://docs.github.com/actions/reference/virtual-environments-for-github-hosted-runners#docker-container-filesystem
      - name: Setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v2 #checkout step
      - name: Install dependencies (pdftk, poppler, imagemagick)
        run: sudo apt install imagemagick pdftk poppler-utils
      - name: Gem Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Dependencies
        run: bundle install --path vendor/bundle
      - name: Setup database
        run: bundle exec rake db:create db:schema:load
      - name: Run Specs
        run: bundle exec rspec --pattern spec/**/*_spec.rb --pattern modules/*/spec/**/*_spec.rb --format progress --format RspecJunitFormatter -o ./rspec/rspec.xml --format html --out ./ci/rspec.html

