name: Trigger Jenkins Deployment
on:
  push:
    branches:
      - 23096-trigger-jenkins-from-gha
jobs:
  trigger_jenkins_deploy:
      name: Trigger jenkins deployment
      runs-on: ubuntu-latest
      steps:
        - name: Trigger Jenkins deployment
          uses: appleboy/jenkins-action@master
          with:
            url: http://dev.va.gov/jenkins
            user: ${{ secrets.JENKINS_USER }}
            token: ${{ secrets.JENKINS_TOKEN }}
            job: vets-gov-autodeploy-vets-api
