name: Trigger Jenkins Deployment
on:
  push:
    branches:
      - 23096-trigger-jenkins-from-gha
jobs:
  trigger_jenkins_deploy:
      name: Trigger jenkins deployment
      runs-on: ubuntu-latest
      steps:
        - name: Deploy vets-api server in dev
          uses: wei/curl@v1
          with:
            args: >
              -X POST -L --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} 
              https://dev.va.gov/jenkins/job/deploys/job/vets-api-server-vagov-dev/build
              --data-urlencode json='{\"parameter\": [
                {\"name\":\"app\",\"value\":\"vets-api-server\"},
                {\"name\":\"notify_slack\",\"value\":true},
                {\"name\":\"environment\",\"value\":\"vagov-dev\"},
                {\"name\":\"migration_status",\"value\":true},
                {\"name\":\"ref\",\"value\":\"${{ github.sha }}\"}
              ]}'
        - name: Deploy vets-api worker in dev
          uses: wei/curl@v1
          with:
            args: >
              -X POST -L --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} 
              https://dev.va.gov/jenkins/job/deploys/job/vets-api-worker-vagov-dev/build
              --data-urlencode json='{"parameter": [
                {"name":"app","value":"vets-api-worker"},
                {"name":"notify_slack","value":true},
                {"name":"environment","value":"vagov-dev"}
              ]}'
        - name: Deploy vets-api server in staging
          uses: wei/curl@v1
          with:
            args: >
              -X POST -L --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} 
              https://dev.va.gov/jenkins/job/deploys/job/vets-api-server-vagov-staging/build
              --data-urlencode json='{"parameter": [
                {"name":"app","value":"vets-api-server"},
                {"name":"notify_slack","value":true},
                {"name":"environment","value":"vagov-staging"}
              ]}'
        - name: Deploys vets-api worker in staging
          uses: wei/curl@v1
          with:
            args: >
              -X POST -L --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} 
              https://dev.va.gov/jenkins/job/deploys/job/vets-api-worker-vagov-staging/build
              --data-urlencode json='{"parameter": [
                {"name":"app","value":"vets-api-worker"},
                {"name":"notify_slack","value":true},
                {"name":"environment","value":"vagov-staging"}
              ]}'
