name: Trigger Jenkins Deployment
on:
  push:
    branches:
      - 23096-trigger-jenkins-from-gha
jobs:
  trigger_jenkins_deploy:
      name: Trigger jenkins deployment
      runs-on: ubuntu-latest
      steps:
        - name: Trigger Jenkins deployment
          uses: wei/curl@v1
          with:
            args: >
              https://dev.va.gov/jenkins/vets-gov-autodeploy-vets-api
              --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}
